# Plugin created by Waind.

empty-player-name: "NONE"

# Time in seconds equal to the sync of the player cards settings with the database
sync-with-sqlite: 1800

# Supported languages: en, ru
lang: en

# %player - get player's displayname %charactername - get player character name, %message - get current message from player
chats:
  # default-range: 15
  action:
    range: 15
    format: "&e*&f%character_name% %character_surname% %message%&e*"

  # default-range: 5
  whisper:
    range: 5
    format: "&7%character_name% %character_surname%: &f%message% &7[&9Whisper&7]"

  # default-range: 35
  shout:
    range: 35
    format: "&7%character_name% %character_surname%: &f%message%&c!"

  # default-range: 15
  default:
    range: 15
    format: "&7%character_name% %character_surname%: &f%message%"

  ooc:
    format: "&f[&cOOC&f] &7%player_name%: &f%message"